name: drm
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.3
  - scipy=1.13.0
  - tensorflow=2.16.1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - deepface==0.0.91
      - filelock==3.9.0
      - fire==0.6.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - fsspec==2024.5.0
      - gast==0.5.4
      - gdown==5.2.0
      - google-pasta==0.2.0
      - grpcio==1.63.0
      - gunicorn==22.0.0
      - h5py==3.11.0
      - huggingface-hub==0.23.0
      - idna==3.7
      - itsdangerous==2.2.0
      - jinja2==3.1.2
      - keras==3.3.3
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - mtcnn==0.1.1
      - namex==0.0.8
      - networkx==3.2.1
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.11.0
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.2.0
      - protobuf==4.25.3
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.31.0
      - retina-face==0.0.17
      - rich==13.7.1
      - safetensors==0.4.3
      - six==1.16.0
      - soupsieve==2.5
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow-intel==2.16.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - tf-keras==2.16.0
      - tokenizers==0.19.1
